services:
  - type: web
    name: sweets-shop
    env: php
    plan: free
    buildCommand: bash render-build.sh
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: PHP_VERSION
        value: "8.2"
